const DEFAULT_LEAGUE = 'Mirage';

const LEAGUES = [
  'Mirage',
  'Hardcore Mirage',
  'Mirage SSF',
  'Hardcore Mirage SSF'
];

// Stack sizes are static game data — update when GGG adds new cards
const CARD_STACK_SIZES = {
  'Abandoned Wealth': 5,
  'Alone in the Darkness': 11,
  'Arrogance of the Vaal': 9,
  "Atziri's Arsenal": 5,
  'Auspicious Ambitions': 10,
  'Baited Expectations': 8,
  'Birth of the Three': 3,
  'Blind Venture': 5,
  'Boon of Justice': 5,
  'Boon of the First Ones': 9,
  'Boundless Realms': 5,
  'Broken Promises': 1,
  'Brotherhood in Exile': 5,
  'Brothers Stash': 5,
  'Call to the First Ones': 5,
  'Chaotic Disposition': 5,
  'Chasing Risk': 5,
  'Death': 4,
  'Desecrated Virtue': 9,
  'Destined to Crumble': 9,
  'Divine Justice': 5,
  'Dying Anguish': 7,
  'Emperor of Purity': 8,
  "Emperor's Luck": 5,
  'Eternity Shroud': 4,
  'Faithful Friend': 12,
  'Fiend': 11,
  'From Bone to Ash': 4,
  'The Gambler': 5,
  'Gift of the Gemling Queen': 9,
  'Gift to the Goddess': 5,
  'Good Work': 7,
  'Grave Knowledge': 8,
  'Harmony of Souls': 9,
  'House of Mirrors': 9,
  'Hubris': 7,
  'Humility': 9,
  'Hunter\'s Reward': 4,
  'Immortal Resolve': 5,
  'Imperial Legacy': 20,
  'Jack in the Box': 4,
  'Judgement': 7,
  'Justified Ambition': 10,
  'Last Hope': 1,
  'Loyalty': 4,
  'Lucky Connections': 5,
  'Lycanthropy': 5,
  'Mawr Blaidd': 9,
  'Merciless Armament': 7,
  'Mindless Brutality': 5,
  'More is Never Enough': 7,
  'No Witnesses': 7,
  'The Nurse': 8,
  'The Offering': 8,
  'Peaceful Moments': 5,
  'Rain Tempter': 5,
  'Rain of Chaos': 8,
  'Rebirth': 8,
  'Rebirth and Renewal': 5,
  'Reckless Ambition': 10,
  'Scholar of the Seas': 5,
  'The Seekers': 8,
  'Shard of Fate': 20,
  'The Silversmith\'s Finest': 5,
  'The Soul': 5,
  'The Surgeon': 4,
  'The Survivalist': 1,
  'The Tireless Extractor': 6,
  'The Tumbleweed': 1,
  'Three Faces in the Dark': 3,
  'The Thousand Faces': 1,
  'Time-Lost Relic': 6,
  'Tranquillity': 10,
  'Treasure Hunter': 9,
  'The Trial': 7,
  'Turn the Other Cheek': 7,
  'The Twins': 6,
  'Uncanny Defence': 6,
  'Unrequited Love': 7,
  'Volatile Power': 7,
  'Void of the Elements': 3,
  'The Void': 1,
  'Warlord\'s Reach': 4,
  'Wealth and Power': 10,
  'The Web': 6,
  'The Wind': 1,
  'The Worm': 1,
  'Apothecary': 5,
  'The Doctor': 8,
  'The Patient': 4,
  'Pride Before the Fall': 10,
  'The Sephirot': 11,
  'The Hoarder': 12,
  'Seven Years Bad Luck': 7,
  'The Fool': 6,
  'The Warden': 10,
  'The Tyrant': 10,
};
